name: Auto Deploy Game Store Backend

on:
  push:
    branches:
      - main  # عدل حسب فرعك

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish API
        run: |
          cd game-store.backend
          dotnet publish -c Release -o publish

      - name: Clean old publish folder on server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 76.13.146.245
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /var/www/api.eng-sy.store*
            mkdir -p /var/www/api.eng-sy.store

      - name: SCP publish folder to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 76.13.146.245
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "game-store.backend/publish/*"
          target: "/var/www/api.eng-sy.store"
          strip_components: 1
          rm: true
          overwrite: true

      - name: Restart service
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 76.13.146.245
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl restart eng-sy.service
