name: Auto Deploy Aljawhara.NET to VPS

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish API
        run: |
          cd Ecom.API
          dotnet publish -c Release -o publish

      - name: SCP publish folder to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 72.61.187.165
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "Ecom.API/publish/*"
          target: "/var/www/Aljawhara.NET/publish"

      - name: Restart service
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 72.61.187.165
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            systemctl restart aljawhara.service
